### ISSUE TITLE
Deprecated error

### ISSUE THREAD

**Issue by Webonaute** [coopTilleuls/CoopTilleulsCKEditorSonataMediaBundle#24]
User Deprecated: The CoopTilleuls\Bundle\CKEditorSonataMediaBundle\Admin\MediaAdminExtension class extends Sonata\AdminBundle\Admin\AdminExtension that is deprecated since version 3.1, to be removed in 4.0. Use Sonata\AdminBundle\AbstractAdminExtension instead

**Comment by meyerbaptiste** [comment]
Fixed in #26
