### ISSUE TITLE
Can i use this bundle without Sonata Admin?

### ISSUE THREAD

**Issue by madmis** [coopTilleuls/CoopTilleulsCKEditorSonataMediaBundle#29]
From documentation i can't understand how use this bundle.
I have configured it (using information from issues). 

But it has a lot of dependencies to Sonata. 
Can i use this bundle without  Sonata Admin? How i can do this?

**Comment by dunglas** [comment]
Hu, this bundle depends of Sonata Media. You cannot use it without SonataMedia.

**Comment by madmis** [comment]
Sure. Thanks.
