### ISSUE TITLE
Remove bundle inheritance

### ISSUE THREAD

**Issue by theMadness** [coopTilleuls/CoopTilleulsCKEditorSonataMediaBundle#33]
Would it be possible to remove bundle inheritance so it can be compatible with symfony 4?

**Comment by dunglas** [comment]
If someone work on this, we will be glad to merge the PR. Unfortunately SF4 compatibility for this bundle is not on our own agenda right now.

**Comment by theMadness** [comment]
Definitely not opposed to work on it, can you give a few pointers/a todo list? I'm not too versed in how to update bundles.
